[package]
name = "gd_save_browser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
base64 = "0.21.2"
flate2 = "1.0.26"
xml-rs = "0.8.14"
iced = "0.9.0"
rfd = "0.11.4"
